name: luanvan
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.3.0
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.8.0
  icons_plus: ^5.0.0
  flutter_staggered_grid_view: ^0.7.0
  carousel_slider: ^5.0.0
  dvhcvn: ^2.1.20250301
  intl: 0.19.0
  flutter_bloc: ^9.1.0
  get_it: 7.7.0
  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.5
  firebase_auth: ^5.5.1
  firebase_storage: ^12.4.4
  firebase_app_check: ^0.3.2+4
  flutter_facebook_auth: ^7.1.1
  google_sign_in: ^6.2.2
  cloudinary: ^1.2.0
  image_picker: ^1.1.2
  video_compress: ^3.1.2
  video_player: ^2.8.1
  flutter_svg: ^2.0.17
  reorderable_grid_view: ^2.2.8
  shared_preferences: ^2.5.2
  # flutter_keyboard_visibility: ^6.0.0
  photo_view: ^0.14.0
  twilio_flutter: ^0.9.0
  fl_chart: ^0.65.0
  image: ^4.3.0
  # tflite_flutter: ^0.9.0
  # tflite_flutter_helper: ^0.2.1
  faker: ^2.1.0
  pdf: ^3.10.7
  printing: ^5.11.1
  path_provider: ^2.1.2
  share_plus: ^10.1.4
  file_picker: ^6.1.1
  file_selector: ^1.0.3
  google_fonts: ^6.1.0
  tflite_flutter: ^0.11.0
  diacritic: ^0.1.6
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/mobilenetv2.tflite
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - .env 
  fonts:
    - family: Noto Sans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSans-Italic.ttf
          style: italic
 
