// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoXj7neI6e9kDctmVAiDamSFq1oOX5CMU',
    appId: '1:318159988845:web:5986c1208d7e98ada2b764',
    messagingSenderId: '318159988845',
    projectId: 'shopapp-7c1fb',
    authDomain: 'shopapp-7c1fb.firebaseapp.com',
    storageBucket: 'shopapp-7c1fb.firebasestorage.app',
    measurementId: 'G-JM98J8BSV9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfE5H7y4VvWGC6rq8nlBUzYk0kFZAZUU4',
    appId: '1:318159988845:android:d710bf6f3b144005a2b764',
    messagingSenderId: '318159988845',
    projectId: 'shopapp-7c1fb',
    storageBucket: 'shopapp-7c1fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDD3poohh8JVX6pHOuauxZ4xYqGWBO45WQ',
    appId: '1:318159988845:ios:409d7fc37b30679fa2b764',
    messagingSenderId: '318159988845',
    projectId: 'shopapp-7c1fb',
    storageBucket: 'shopapp-7c1fb.firebasestorage.app',
    iosBundleId: 'com.example.luanvan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDD3poohh8JVX6pHOuauxZ4xYqGWBO45WQ',
    appId: '1:318159988845:ios:409d7fc37b30679fa2b764',
    messagingSenderId: '318159988845',
    projectId: 'shopapp-7c1fb',
    storageBucket: 'shopapp-7c1fb.firebasestorage.app',
    iosBundleId: 'com.example.luanvan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoXj7neI6e9kDctmVAiDamSFq1oOX5CMU',
    appId: '1:318159988845:web:5fa252551c5cf680a2b764',
    messagingSenderId: '318159988845',
    projectId: 'shopapp-7c1fb',
    authDomain: 'shopapp-7c1fb.firebaseapp.com',
    storageBucket: 'shopapp-7c1fb.firebasestorage.app',
    measurementId: 'G-5J8C6DF096',
  );
}
